    name: 🧩 Feature Request
    title: "Feature: {{ title }} "
    description: >
      Describe the new feature you’d like to add to OpenHudle.
    body:
      - type: markdown
        text: |
          ## 🎯 Summary
          A concise description of the feature.
      - type: textarea
        id: user_story
        attributes:
          label: User Story
          description: "As a [user], I want to [goal] so that [reason]."
      - type: dropdown
        id: sprint
        attributes:
          label: Sprint
          options:
            - Sprint 1 – Foundation
            - Sprint 2 – Teams & Permissions
            - Sprint 3 – Video Player & Annotations
            - Sprint 4 – Clips & Tagging
            - Sprint 5 – Playbook & Analytics
            - Sprint 6 – Polish & Scale
      - type: dropdown
        id: area
        attributes:
          label: Area
          options:
            - Frontend
            - Backend
            - Infrastructure
            - Video Processing
            - Realtime
            - Auth
            - Database
            - Documentation
      - type: dropdown
        id: priority
        attributes:
          label: Priority
          options:
            - 🔴 High
            - 🟡 Medium
            - 🟢 Low
      - type: textarea
        id: acceptance_criteria
        attributes:
          label: Acceptance Criteria
          description: "List what conditions must be met for this feature to be considered complete."
